language: python
python: "3.7"

branches:
  only:
#    - master
#    - /^release-.*$/
    - develop

install:
  - python -m pip install --upgrade pip --force-reinstall
  - pip install setuptools==59.5.0
  - pip install -r requirements.txt
  after_failure:
    - echo "PRE-BUILDING stage - failed"
  after_success:
    - echo "PRE-BUILDING stage - done"

script:
  - export PYTHONPATH="$PWD;$PWD/tksbrokerapi;$PWD/tests"
#  - py.test tests -v --disable-pytest-warnings
  after_failure:
    - echo "UNITTEST stage - failed"
  after_success:
    - echo "UNITTEST stage - done"

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    all_branches: true
  skip_cleanup: true
  after_failure:
    - echo "BUILD and PUBLISH to PyPI stages - failed"
  after_success:
    - echo "BUILD and PUBLISH to PyPI stage - done"
