language: python
python: "3.7"
branches:
  only:
#  - master
#  - /^release-.*$/
  - develop

install:
  - python -m pip install --upgrade pip --force-reinstall
  - pip install setuptools==59.5.0
  - pip install -r requirements.txt

script:
  - export PYTHONPATH="$PWD;$PWD/tksbrokerapi;$PWD/tests"
#  - py.test tests -v --disable-pytest-warnings

deploy:
  provider: pypi
  username: __token__
  password:
    secure: "dLeACO8w1kU/U87ntKkjNf6Dt0n7kHetjRXci3/dc5Htim+AuOeGVLFO7qOGAbJaFhVWR//lGxyrHrB7R9O6M9+87XVARXJUSqOI1Edj+JLdF2vuGcq4T9BFQchIflD2yfKRPiV8O9pvbtzNMWMt5eStg0UcKMARXsAh5beB+Rln5aN86Fhz2+C/fEc7wARrM2QKqTkd5z78B4pdxmd0fBQQflJLg+ydgtjDmoEoeEEtmIqu4l8qvk13YsUx/cutFmG0wltBEGQvvglZQ78ZaYS7SZ50QuYNN49BAFNMa6IrrvSOHy3JvfL3XqEdwlRqirS8AwcDPIa86TltN+XnJLJjl3AIkqiXV5NKTrGhtzUR6I86mbiEcgtCowtB6UH/DInX6EO1fs6jMjeT1zD4VjLa3NzHxqpIrxrXUzmU/ljPkdxlCH3jlNM5zrVxNJv+ySTX4A2w4qZzvneXqJshqgnwQYXWzP92mqhVD/ob4229hakztc+8bTq2Hu9tv7pezV1lCXpa7Wi5maAmbtxMktLS/KpVIEz5mNYVFxki47o/nDkeJObj6qFimf0GeIFeCSVR7rfmsj5pt9tDIfSE/nf1Wd8MXBpa3FhKvQsq/WjC+vofbP9hXIzk0VHjqciSpffbH1stZoVQn4VNmLxBcf7EUMf9wRu6wphq+coXcPM="
  distributions: sdist bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true

after_failure:
  - echo "Some issues occurred"

after_success:
  - echo "Publish TKSBrokerAPI packet to PyPI - done"
