language: python
python: "3.7"
branches:
  only:
#    - master
#    - /^release-.*$/
    - develop

install:
  - python -m pip install --upgrade pip --force-reinstall
  - pip install setuptools==59.5.0
  - pip install -r requirements.txt

script:
  - export PYTHONPATH="$PWD;$PWD/tksbrokerapi;$PWD/tests"
#  - py.test tests -v --disable-pytest-warnings

deploy:
  provider: pypi
  username: __token__
  password:
    secure: TzyUtH0YMP6PgtMmFytyi7WhgOcKlC3Yr1iD/oNY12uym7kKnOsN9hIiQGYi111YdnOY4lcGu73nlT8JchC5NPQ+ysTCJR5Yux1eK4PfS0Mb06Y5bw2UPeusbjgYyTaftqTDFHrLAGZpYYs0G4w35WHBUFd/L5wr+v4IA0ZvHtr7x7GHAsTyj4lPAkTp5rpu5faqux5LzxA5zQol25HaYoxbIyKpjLziwyzxdfiY81u+ArbHjrgyNrDq7nrXODihBcC6t+CPucUsjPQgqcKoiu2Y48901rEOYVsNk/hcWDiAIarpPTbxjFPmf0Y8YowMGUW5kObWT0b+aDmJYsR5ElGdrdliNFuqaZQXLME1BZpEs0zyXMiMC3FI1/4WIQ+hx2R2Kcr5nh047u/1JhmqSYhHu/cZG9tmp4HxwXiM6mWDlldgYU9rXvECuZU/5bLAloLjO5aJxfnCPBWtvA/JUhzH2tUDUto5+tHHF37HI0VYIlpRt+Ttu1i3tUDqfkTgc8e/VshHPGvgucPzAs5JDo5Dc1/yqPsWEbmbsbuNrRHKhnhxvZK8FZ4skvuB5CkiVdVMH0nO4cae8CP76PzBMWImeh2b80OGeewiMa+OIgQxX/6BnG6UpsRybUOtzea35LN3fZsyHcmKuJemnbGI4cxIwj4H5Aj0OLN0phSUk4w=
  distributions: sdist bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true

after_failure:
  - echo "Some issues occurred"

after_success:
  - echo "Publish TKSBrokerAPI packet to PyPI - done"
