language: python
python: "3.7"
branches:
  only:
#    - master
#    - /^release-.*$/
    - develop

install:
  - python -m pip install --upgrade pip --force-reinstall
  - pip install setuptools==59.5.0
  - pip install -r requirements.txt

script:
  - export PYTHONPATH="$PWD;$PWD/tksbrokerapi;$PWD/tests"
#  - py.test tests -v --disable-pytest-warnings

deploy:
  provider: pypi
  edge: true
  username: __token__
  password: K80HnQ7JaLpMXZKfkNRHST8Oyfp6CaFTNDhArlBXGex+tpw7sN0aPM6+96oUDrOPGa+mYD3VobYK7jH6xDP/cABfUc8bc/h6lLcAQo/ynbUsykAvw5yH7AlMREyrpIq9Y/tfNG3YBpmGgzY4rkl+8BxV2dRmeHzzL+8YPenE6vyNMT/X+MAqd1Srd1o+wV0UPxgEKN2TFCc1fntEehkp0DzX/Cqgm1UG3LCyzWVUF9nB7dkx0MdUkB7LzL3mWsy2HGiZ6fDH0XtA4t6txG3saU65gzSzaBFtvVqulGj1+iCKJKQhLAn8eNUhioGR/0ZlsvNCwpNSwiAey9oKndA8JnYwVjzgCANKhpYKdFtr7QZJfvTuPiL2D0SUStNVVWfkH9crA1qZVZYfC2alf0fWAf+OS2nUQmHzgwT58rWMrIa31ltrGg2sw6R03sX3tT6QzJDFJziuJ123J5McWVzqUxawdOLu3dZ/3hGxCE7fWF0FsZpwUiKSCZ4f/IpFLOVl+Ro8C9RuL4AlE1NJOE7m+VK3mK4LDRm2gOaJNcP4A7oi4dq5B6iGEVHWqxiRU2utf4r4Unp1S1LYXd6GTCo+F+nGQFt8KfuTHNxhhjDbJo/wDhbkIUh1iFFzzdmIdxMdAtUuY7Vgxz6Vp3ckna09m7XbWxcxxA1uQ7FFF5ot+2U=
  distributions: sdist bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true

after_failure:
  - echo "Some issues occurred"

after_success:
  - echo "Publish TKSBrokerAPI packet to PyPI - done"
