language: python
python: "3.7"

branches:
  only:
    - master
    - /^release-.*$/
    - develop

stages:
  - env-test-build-publish

jobs:
  include:
    - stage: env-test-build-publish
      name: "PRE-BUILDING - TESTING - BUILDING - PUBLISHING to PyPI"
      install:
        - python -m pip install --upgrade pip --force-reinstall
        - pip install setuptools==59.5.0
        - pip install -r requirements.txt
      before_script:
        - export PYTHONPATH=$PYTHONPATH:$PWD:$PWD/tksbrokerapi:$PWD/tests
      script:
        - pytest tests -v --disable-pytest-warnings
      deploy:
        provider: pypi
        distributions: "sdist bdist_wheel"
        on:
          all_branches: true
        skip_cleanup: true
      after_failure:
        - echo "Some issues occurred when building. See full logs."
      after_success:
        - echo "All build steps - done"
